name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file apirest/pom.xml

    # Si las pruebas fallan, subir los reportes para revisarlos
    - name: Upload Surefire Test Reports
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: surefire-reports
        path: apirest/target/surefire-reports
